"use client";

import Head from "next/head";
import NewPost from "@/components/NewPost";

export default function Timeline() {
  return (
    <>
      <Head>
        <title>CryptX | Timeline</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container">
        <div className="row">
            <div className="layout">
                <NewPost />
            </div>
        </div>
      </div>
    </>
  );
}
