"use client";

import Head from "next/head";
import { doLogin } from "@/services/Web3Service";
import { useState } from "react";
import Footer from "../components/Footer";

export default function Home() {

  const [message, setMessage] = useState("");

  function btnLoginClick() {
    setMessage("Connecting to Metamask...");
    doLogin()
      .then(wallet => setMessage(wallet))
      .catch(err => setMessage.error(err))
  }

  return (
    <>
      <Head>
        <title>CryptX</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container px-4 py-5">
        <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
          <div className="col-10 col-sm-8 col-lg-6">
            <img src="https://images.unsplash.com/photo-1519114563721-eb52c00b9129?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" className="d-block mx-lg-auto img-fluid shadow p-3 mb-5 bg-body rounded" width="700" height="500" />
          </div>
          <div className="col-lg-6">
            <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-4">Crypt<i>X</i></h1>
            <p className="lead">Your <u><i>decentralized</i></u> Social Network.</p>
            <p className="lead mb-4">Join with your wallet and let the world know how you're feeling!</p>
            <div className="d-grid gap-2 d-md-flex justify-content-md-start ">
              <button type="button" className="btn btn-primary btn-lg px-4 me-md-2" onClick={btnLoginClick}>
                <img src="/metamask.png" width="64" className="me-3"/>
                Connect with Metamask
              </button>
            </div>
            <p className="message">{message}</p>
          </div>
        </div>
        <Footer />
      </div>
    
    </>
    
  );
}
